# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{cron: "0 7 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          config_timezone: Europe/Paris
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          extras_css: |
            .avatar,h1 span {
              display:none;!important
            }

      - name: Repositories traffic
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.traffic.svg
          config_timezone: Europe/Paris
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes

      - name: Succint report
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.svg
          config_timezone: Europe/Paris
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://www.mehdihilmi.fr
          
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          config_timezone: Europe/Paris
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}


      - name: Update this repo's README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          SHOW_TITLE: true 
          COMMIT_MESSAGE: Waka Updated         
          SHOW_TOTAL: true
          # SHOW_TIME: false